//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallBizReceiptTrackingAPI.Repositories.Models
{
    using System;
    
    internal partial class DBUser
    {
        public int UserID { internal get; set; }
        public string FirstName { internal get; set; }
        public string LastName { internal get; set; }
        public int CompanyID { internal get; set; }
        public int AddressID { internal get; set; }
        public bool IsPrimaryCompanyContact { internal get; set; }
    }
}
