//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallBizReceiptTrackingAPI.Repositories.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    /// <summary>
    /// SmallBizReceiptTrackingEntities data object
    /// </summary>
    public partial class SmallBizReceiptTrackingEntities : DbContext
    {
    	/// <summary>
    	/// Constructs a new instance of the SmallBizReceiptTrackingEntities object
    	/// </summary>
        public SmallBizReceiptTrackingEntities()
            : base("name=SmallBizReceiptTrackingEntities")
        {
        }
    	
    
        internal virtual ObjectResult<DBUser> GetUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DBUser>("GetUsers");
        }
    }
}
